algoritmo "ContaNegativos"
// Função :
// Autor :
// Data : 30/10/2023
// Seção de Declarações 
var
   N, C, TotN: Inteiro
inicio
      C <- 1
      TotN <- 0
      Repita
            Escreva ("Digite um número: ")
            Leia (N)
            Se ( N < 0 ) entao
            TotN < - Totn +1
            Fimse
            C < - C + 1
      Ate (C > 5)
      Escreval ("Foram digitados ", TotN, "valores negativos. ")
fimalgoritmo
