algoritmo "Somador"
// Função :
// Autor :
// Data : 30/10/2023
// Seção de Declarações 
var
   N, Cont, S: Inteiro
inicio
      S <- 0
      Cont <- 1
      Enquanto (Cont <=5) faca
               Escreva ("Digite o ", Cont, "°. valor ==>")
               Leia (N)
               S <- S + N
               Cont <- Cont + 1
      Fimenquanto
      Escreval ("A soma de todos os valores digitados é ", S)
fimalgoritmo
